import { Router } from "express";
import { authRouter } from "../modules/auth/auth.controller.js";
import { contentRouter } from "../modules/content/content.controller.js";
import { progressRouter } from "../modules/progress/progress.controller.js";
import { gameRouter } from "../modules/game/game.controller.js";
import { leaderboardRouter } from "../modules/leaderboard/leaderboard.controller.js";
import { socialRouter } from "../modules/social/social.controller.js";
import { communityRouter } from "../modules/community/community.controller.js";
import { notificationsRouter } from "../modules/notifications/notifications.controller.js";
import { searchRouter } from "../modules/search/search.controller.js";
import { moderationRouter } from "../modules/moderation/moderation.controller.js";
import { feedbackRouter } from "../modules/feedback/feedback.controller.js";
import { quizRouter } from "../modules/quiz/quiz.controller.js";
import { collectionsRouter } from "../modules/collections/collections.controller.js";
import { pushRouter } from "../modules/push/push.controller.js";
import { achievementsRouter } from "../modules/achievements/achievements.controller.js";
import { usersRouter } from "../modules/users/users.controller.js";
import storageRouter from "../modules/storage/storage.controller.js";
import gamificationRouter from "../modules/gamification/gamification.controller.js";
import { gamificationAdminRouter } from "../modules/admin/controllers/gamification.admin.controller.js";
import { feedbackAdminRouter } from "../modules/admin/controllers/feedback.admin.controller.js";
import { moderationAdminRouter } from "../modules/admin/controllers/moderation.admin.controller.js";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/content", contentRouter);
apiRouter.use("/progress", progressRouter);
apiRouter.use("/game", gameRouter);
apiRouter.use("/leaderboard", leaderboardRouter);
apiRouter.use("/social", socialRouter);
apiRouter.use("/community", communityRouter);
apiRouter.use("/notifications", notificationsRouter);
apiRouter.use("/search", searchRouter);
apiRouter.use("/moderation", moderationRouter);
apiRouter.use("/feedback", feedbackRouter);
apiRouter.use("/quiz", quizRouter);
apiRouter.use("/collections", collectionsRouter);
apiRouter.use("/push", pushRouter);
apiRouter.use("/achievements", achievementsRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/storage", storageRouter);
apiRouter.use("/gamification", gamificationRouter);
apiRouter.use("/admin/gamification", gamificationAdminRouter);
apiRouter.use("/admin/feedback", feedbackAdminRouter);
apiRouter.use("/admin/moderation", moderationAdminRouter);
